apiVersion: v1
kind: Pod
metadata:
  name: blue-pod
  namespace: prod
  labels:
    app:   stack
    stack: blue
spec:
  containers:
  - name:  nginx-container
    image: nginx
    ports:
      - containerPort: 80
