apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-cluster
  region: ap-northeast-1
  version: "1.31"
managedNodeGroups:
  - name: my-nodes
    instanceType: t3.small
    desiredCapacity: 2
    privateNetworking: true
vpc:
  subnets:
    public:
      ap-northeast-1a:
        id: "subnet-0b10715b2edf27dde"
      ap-northeast-1c:
        id: "subnet-023105dfe3f0a2bdb"
    private:
      ap-northeast-1a:
        id: "subnet-05b9ed847f67bd0e1"
      ap-northeast-1c:
        id: "subnet-0318a86c9486e9ea9"
  clusterEndpoints:
    publicAccess:  true
    privateAccess: false
