apiVersion: v1
kind: Pod
metadata:
  name: p1
  namespace: namespace2
  labels:
    app: webapp
spec:
  containers:
  - name:  nginx-container
    image: nginx:1.25.1
    ports:
      - containerPort: 80
      