apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
  - name: container-a
    image: nginx:1.25.1
    ports:
      - containerPort: 80
    resources:
      requests:
        memory: "600Mi"
        cpu: "400m"
      limits:
        memory: "800Mi"
        cpu: "800m"
  - name: container-b
    image: ubuntu:18.04
    command: ["tail", "-F", "/dev/null"]
    resources:
      requests:
        memory: "600Mi"
        cpu: "600m"
      limits:
        memory: "800Mi"
        cpu: "800m"